import os
import psutil
import time
import logging

logger = logging.getLogger("ai_core.resource_monitor")

class ResourceMonitor:
    """
    Monitors CPU and RAM usage specifically for the ANTIPOVERTI 'brain' processes:
    - Current Python process (AI Core)
    - Rust Engine process (Engine.exe)
    
    Estimates power consumption based on CPU load.
    """
    
    def __init__(self, tdp_watts=65):
        self.tdp_watts = tdp_watts
        self.this_proc = psutil.Process(os.get_pid())
        self.engine_proc = None
        self._find_engine_process()
        
    def _find_engine_process(self):
        """Locate the Rust Engine.exe process."""
        for proc in psutil.process_iter(['name']):
            try:
                if proc.info['name'] and proc.info['name'].lower() == 'engine.exe':
                    self.engine_proc = proc
                    logger.info(f"Found Rust Engine process: PID {proc.pid}")
                    return
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                continue
        logger.warning("Rust Engine process not found. Will retry in next poll.")

    def get_metrics(self):
        """Collect metrics for the 'brain' only."""
        if self.engine_proc is None or not self.engine_proc.is_running():
            self._find_engine_process()
            
        procs = [self.this_proc]
        if self.engine_proc:
            procs.append(self.engine_proc)
            
        total_cpu_percent = 0.0
        total_ram_mb = 0.0
        
        for p in procs:
            try:
                # interval=None for non-blocking since we poll periodically
                total_cpu_percent += p.cpu_percent(interval=None)
                total_ram_mb += p.memory_info().rss / (1024 * 1024)
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                continue

        # Power Estimation:
        # P_total = P_idle + (P_max - P_idle) * (CPU_load / 100)
        # For 'additional' power used by brain:
        # P_brain = TDP * (CPU_brain_load / 100) 
        # This is a simplified model for 'extra load generated by brain'
        estimated_watts = (total_cpu_percent / 100.0) * self.tdp_watts
        
        return {
            "cpu_percent": round(total_cpu_percent, 1),
            "ram_mb": round(total_ram_mb, 1),
            "estimated_watts": round(estimated_watts, 2)
        }

if __name__ == "__main__":
    # Test execution
    monitor = ResourceMonitor()
    while True:
        print(f"Brain Metrics: {monitor.get_metrics()}")
        time.sleep(1)
